# Generated by Django 3.2.12 on 2022-02-22 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_petmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=250)),
            ],
        ),
        # migrations.AddField(
        #     model_name='question',
        #     name='category',
        #     field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app.category'),
        # ),
    ]
